
export default {
  level0:{"player":{"level":{"val":0,"toNext":15,"toNextMax":15},"hp":{"val":100,"max":100,"base":100,"levelModifier":0,"extraHeartMultiplier":0},"attack":{"val":10,"base":10,"levelModifier":0,"artifactMultiplier":0,"extraBeeftMultiplier":0,"fangsMultiplier":0},"defence":{"val":0},"poisonDefence":{"val":0,"antigens":0},"fourthDefence":{"val":0,"flat":0,"antiJoust":0},"crit":{"val":0,"base":0},"hit":{"val":100,"base":100},"evade":{"val":0,"base":0},"thorns":{"val":0},"absorb":{"val":0},"anger":{"val":0,"increase":0},"deathDefy":{"count":0,"newHp":0},"poisonAttack":{"val":0,"base":0,"artifactMultiplier":0,"centepedeForcipules":0,"chance":5,"chanceBase":5,"anaphylaxis":0,"formicAcid":0,"fangs":false},"toxin":{"val":0,"base":0,"necrosis":0},"strongFourth":{"val":0,"flat":0,"joust":0},"firstStrike":false,"goldGain":{"val":100,"base":100,"lobsterGreed":0},"expGain":{"val":100,"base":100,"shrimpWisdom":0},"atb":{"val":0,"max":5000,"speed":200,"longerLegs":0},"recovery":{"val":5,"atb":{"val":0,"max":5000,"speed":200}},"curses":{"poison":0},"resources":{"gold":0,"sp":0}},"skills":{"extraHeart":0,"extraBeef":0,"longerLegs":0,"superiorVision":0,"centepedeForcipules":0,"anaphylaxis":0,"formicAcid":0,"fangs":0,"lobsterGreed":0,"shrimpWisdom":0,"necrosis":0,"antigens":0,"joust":0,"antiJoust":0}},
  level4:{"player":{"level":{"val":4,"toNext":35,"toNextMax":35},"hp":{"val":112,"max":112,"base":100,"levelModifier":12,"extraHeartMultiplier":0},"attack":{"val":13,"base":10,"levelModifier":3,"artifactMultiplier":0,"extraBeefMultiplier":0,"fangsMultiplier":0},"defence":{"val":0},"poisonDefence":{"val":0,"antigens":0},"fourthDefence":{"val":0,"flat":0,"antiJoust":0},"crit":{"val":0,"base":0},"hit":{"val":100,"base":100},"evade":{"val":0,"base":0},"thorns":{"val":0},"absorb":{"val":0},"anger":{"val":0,"increase":0},"deathDefy":{"count":0,"newHp":0},"poisonAttack":{"val":0,"base":0,"artifactMultiplier":0,"centepedeForcipules":0,"chance":5,"chanceBase":5,"anaphylaxis":0,"formicAcid":0,"fangs":false},"toxin":{"val":0,"base":0,"necrosis":0},"strongFourth":{"val":0,"flat":0,"joust":0},"firstStrike":false,"goldGain":{"val":100,"base":100,"lobsterGreed":0},"expGain":{"val":100,"base":100,"shrimpWisdom":0},"atb":{"val":0,"max":5000,"speed":200,"longerLegs":0},"recovery":{"val":5,"atb":{"val":0,"max":5000,"speed":200}},"curses":{"poison":0},"resources":{"gold":80,"sp":4,"spSpent":0}},"skills":{"extraHeart":0,"extraBeef":0,"longerLegs":0,"superiorVision":0,"centepedeForcipules":0,"anaphylaxis":0,"formicAcid":0,"fangs":0,"lobsterGreed":0,"shrimpWisdom":0,"necrosis":0,"antigens":0,"joust":0,"antiJoust":0},"storyProgress":{"gateKeeperDefeated":false,"miasmoDefeated":false}},
  level8:{"player":{"level":{"val":8,"toNext":999999996,"toNextMax":999999999},"hp":{"val":167,"max":167,"base":100,"levelModifier":29,"extraHeartMultiplier":0.3},"attack":{"val":14,"base":10,"levelModifier":4,"artifactMultiplier":0,"extraBeefMultiplier":0,"fangsMultiplier":0},"defence":{"val":0},"poisonDefence":{"val":0,"antigens":0},"fourthDefence":{"val":0,"flat":0,"antiJoust":0},"crit":{"val":0,"base":0},"hit":{"val":100,"base":100},"evade":{"val":0,"base":0},"thorns":{"val":0},"absorb":{"val":0},"anger":{"val":0,"increase":0},"deathDefy":{"count":0,"newHp":0},"poisonAttack":{"val":0,"base":0,"artifactMultiplier":0,"centepedeForcipules":0,"chance":5,"chanceBase":5,"anaphylaxis":0,"formicAcid":0,"fangs":false},"toxin":{"val":0,"base":0,"necrosis":0},"strongFourth":{"val":0,"flat":0,"joust":0},"firstStrike":false,"goldGain":{"val":100,"base":100,"lobsterGreed":0},"expGain":{"val":100,"base":100,"shrimpWisdom":0},"atb":{"val":0,"max":5000,"speed":200,"longerLegs":0},"recovery":{"val":5,"atb":{"val":0,"max":5000,"speed":200}},"curses":{"poison":0},"resources":{"gold":220,"sp":5,"spSpent":3}},"skills":{"extraHeart":1,"extraBeef":0,"longerLegs":0,"superiorVision":0,"centepedeForcipules":0,"anaphylaxis":0,"formicAcid":0,"fangs":0,"lobsterGreed":0,"shrimpWisdom":0,"necrosis":0,"antigens":0,"joust":0,"antiJoust":0},"storyProgress":{"gateKeeperDefeated":true,"miasmoDefeated":false}},
  


}

